/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */
/* Template located at tools/gen/print_header_template */
#ifndef LIGHTNING_TOOLS_TEST_GEN_PRINT_H
#define LIGHTNING_TOOLS_TEST_GEN_PRINT_H
#include <ccan/tal/tal.h>
#include <devtools/print_wire.h>
#include <ccan/short_types/short_types.h>
#include "enum.h"

void printtest_type_message(const u8 *msg);

void printtest_type_tlv_message(const char *tlv_name, const u8 *msg);

void printwire_test_msg(const char *fieldname, const u8 *cursor);

void printwire_test_ifdef(const char *fieldname, const u8 *cursor);

void printwire_test_tlv1(const char *fieldname, const u8 *cursor);

void printwire_test_tlv2(const char *fieldname, const u8 *cursor);

void printwire_test_tlv3(const char *fieldname, const u8 *cursor);


#endif /* LIGHTNING_TOOLS_TEST_GEN_PRINT_H */

