#include "gen_test.h"
/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */

#include "tools/test/gen_print.h"
#include <ccan/array_size/array_size.h>
#include <ccan/mem/mem.h>
#include <ccan/tal/str/str.h>
#include <common/utils.h>
#include <inttypes.h>
#include <stdio.h>

void printtest_type_message(const u8 *msg)
{
	switch ((enum test_type)fromwire_peektype(msg)) {
		case WIRE_TEST_MSG:
			printf("WIRE_TEST_MSG:\n");
			printwire_test_msg("test_msg", msg);
			return;
		case WIRE_TEST_TLV1:
			printf("WIRE_TEST_TLV1:\n");
			printwire_test_tlv1("test_tlv1", msg);
			return;
		case WIRE_TEST_IFDEF:
			printf("WIRE_TEST_IFDEF:\n");
			printwire_test_ifdef("test_ifdef", msg);
			return;
		case WIRE_TEST_TLV2:
			printf("WIRE_TEST_TLV2:\n");
			printwire_test_tlv2("test_tlv2", msg);
			return;
		case WIRE_TEST_TLV3:
			printf("WIRE_TEST_TLV3:\n");
			printwire_test_tlv3("test_tlv3", msg);
			return;
	}

	printf("UNKNOWN: %s\\n", tal_hex(msg, msg));
}

  
static void printwire_subtype_var_assign(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	u8 len_1 = fromwire_u8(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("field_1=");
	printf("[");
	for (size_t i = 0; i < len_1; i++) {
		u16 v;
		v = fromwire_u16(cursor, plen);
		if (!*cursor) {
			printf("**TRUNCATED**\n");
			return;
		}
		printwire_u16(tal_fmt(NULL, "%s.field_1", fieldname), &v);
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static void printwire_test_features(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	u16 len_lf = fromwire_u16(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("localfeatures=");
	printwire_u8_array(tal_fmt(NULL, "%s.localfeatures", fieldname), cursor, plen, len_lf);

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u16 len_gf = fromwire_u16(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("globalfeatures=");
	printwire_u8_array(tal_fmt(NULL, "%s.globalfeatures", fieldname), cursor, plen, len_gf);

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static void printwire_test_short_id(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	printf("u64=");
	u64 u64 = fromwire_u64(cursor, plen);
	
	printwire_u64(tal_fmt(NULL, "%s.u64", fieldname), &u64); 
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static void printwire_subtype_nested(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	printf("field_1=");
	printf("{\n");
	printwire_test_short_id(tal_fmt(NULL, "%s.field_1", fieldname), cursor, plen);
	printf("}\n");

}

static void printwire_subtype_varlen_varsize(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	u8 len = fromwire_u8(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("field_1=");
	printf("[");
	for (size_t i = 0; i < len; i++) {
		printf("{\n");
		printwire_test_features(tal_fmt(NULL, "%s.field_1", fieldname), cursor, plen);
		printf("}\n");
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static void printwire_subtype_arrays(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	printf("field1=");
	printwire_u8_array(tal_fmt(NULL, "%s.field1", fieldname), cursor, plen, 2);

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("field2=");
	printf("[");
	for (size_t i = 0; i < 2; i++) {
		u16 v;
		v = fromwire_u16(cursor, plen);
		if (!*cursor) {
			printf("**TRUNCATED**\n");
			return;
		}
		printwire_u16(tal_fmt(NULL, "%s.field2", fieldname), &v);
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("field3=");
	printf("[");
	for (size_t i = 0; i < 2; i++) {
		printf("{\n");
		printwire_test_short_id(tal_fmt(NULL, "%s.field3", fieldname), cursor, plen);
		printf("}\n");
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static void printwire_subtype_var_len(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	u8 len_2 = fromwire_u8(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("field_2=");
	printf("[");
	for (size_t i = 0; i < len_2; i++) {
		printf("{\n");
		printwire_test_short_id(tal_fmt(NULL, "%s.field_2", fieldname), cursor, plen);
		printf("}\n");
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static void printwire_subtype_varsize_struct(const char *fieldname, const u8 **cursor, size_t *plen)
{
	
	printf("field_0=");
	printf("{\n");
	printwire_test_features(tal_fmt(NULL, "%s.field_0", fieldname), cursor, plen);
	printf("}\n");

}

static void printwire_tlv_test_n2_tlv2(const char *fieldname, const u8 **cursor, size_t *plen)
{
	printf("(msg_name=%s)\n", "tlv2");
	
	printf("cltv_expiry=");
	u32 cltv_expiry = fromwire_tu32(cursor, plen);
	
	printwire_u32(tal_fmt(NULL, "%s.cltv_expiry", fieldname), &cltv_expiry); 
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}
static void printwire_tlv_test_n2_tlv1(const char *fieldname, const u8 **cursor, size_t *plen)
{
	printf("(msg_name=%s)\n", "tlv1");
	
	printf("amount_msat=");
	u64 amount_msat = fromwire_tu64(cursor, plen);
	
	printwire_u64(tal_fmt(NULL, "%s.amount_msat", fieldname), &amount_msat); 
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static const struct tlv_print_record_type print_tlvs_test_n2[] = {
	{ 11, printwire_tlv_test_n2_tlv2 },
	{ 0, printwire_tlv_test_n2_tlv1 },
};

static void printwire_tlv_test_n3_tlv3(const char *fieldname, const u8 **cursor, size_t *plen)
{
	printf("(msg_name=%s)\n", "tlv3");
	
	printf("subtype=");
	printf("{\n");
	printwire_test_short_id(tal_fmt(NULL, "%s.subtype", fieldname), cursor, plen);
	printf("}\n");
	printf("varlen_subtype=");
	printf("{\n");
	printwire_subtype_var_len(tal_fmt(NULL, "%s.varlen_subtype", fieldname), cursor, plen);
	printf("}\n");
	printf("varlen_assigned=");
	printf("{\n");
	printwire_subtype_var_assign(tal_fmt(NULL, "%s.varlen_assigned", fieldname), cursor, plen);
	printf("}\n");
	printf("test_sbt_varlen_varsize=");
	printf("{\n");
	printwire_subtype_varlen_varsize(tal_fmt(NULL, "%s.test_sbt_varlen_varsize", fieldname), cursor, plen);
	printf("}\n");
	printf("arr_assign=");
	printf("[");
	for (size_t i = 0; i < 2; i++) {
		u32 v;
		v = fromwire_u32(cursor, plen);
		if (!*cursor) {
			printf("**TRUNCATED**\n");
			return;
		}
		printwire_u32(tal_fmt(NULL, "%s.arr_assign", fieldname), &v);
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("arr_struct=");
	printf("[");
	for (size_t i = 0; i < 2; i++) {
		printf("{\n");
		printwire_test_short_id(tal_fmt(NULL, "%s.arr_struct", fieldname), cursor, plen);
		printf("}\n");
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u16 len_lf = fromwire_u16(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("localfeatures=");
	printwire_u8_array(tal_fmt(NULL, "%s.localfeatures", fieldname), cursor, plen, len_lf);

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u16 len_varlen_ass = fromwire_u16(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("varlen_ass=");
	printf("[");
	for (size_t i = 0; i < len_varlen_ass; i++) {
		u64 v;
		v = fromwire_u64(cursor, plen);
		if (!*cursor) {
			printf("**TRUNCATED**\n");
			return;
		}
		printwire_u64(tal_fmt(NULL, "%s.varlen_ass", fieldname), &v);
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u8 len_varlen = fromwire_u8(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("varlen_struct=");
	printf("[");
	for (size_t i = 0; i < len_varlen; i++) {
		printf("{\n");
		printwire_test_short_id(tal_fmt(NULL, "%s.varlen_struct", fieldname), cursor, plen);
		printf("}\n");
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u8 len_varlenvarsize = fromwire_u8(cursor, plen);
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("varlen_varsize=");
	printf("[");
	for (size_t i = 0; i < len_varlenvarsize; i++) {
		printf("{\n");
		printwire_test_features(tal_fmt(NULL, "%s.varlen_varsize", fieldname), cursor, plen);
		printf("}\n");
	}
	printf("]");

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("remainder=");
	printwire_u8_array(tal_fmt(NULL, "%s.remainder", fieldname), cursor, plen, *plen);

	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static const struct tlv_print_record_type print_tlvs_test_n3[] = {
	{ 1, printwire_tlv_test_n3_tlv3 },
};

static void printwire_tlv_test_n1_tlv3(const char *fieldname, const u8 **cursor, size_t *plen)
{
	printf("(msg_name=%s)\n", "tlv3");
	
	printf("features=");
	printf("{\n");
	printwire_test_features(tal_fmt(NULL, "%s.features", fieldname), cursor, plen);
	printf("}\n");
	printf("amount_msat_1=");
	struct amount_msat amount_msat_1 = fromwire_amount_msat(cursor, plen);
	
	printwire_amount_msat(tal_fmt(NULL, "%s.amount_msat_1", fieldname), &amount_msat_1); 
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("amount_msat_2=");
	struct amount_msat amount_msat_2 = fromwire_amount_msat(cursor, plen);
	
	printwire_amount_msat(tal_fmt(NULL, "%s.amount_msat_2", fieldname), &amount_msat_2); 
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}
static void printwire_tlv_test_n1_tlv2(const char *fieldname, const u8 **cursor, size_t *plen)
{
	printf("(msg_name=%s)\n", "tlv2");
	
	printf("scid=");
	printf("{\n");
	printwire_test_short_id(tal_fmt(NULL, "%s.scid", fieldname), cursor, plen);
	printf("}\n");

}
static void printwire_tlv_test_n1_tlv4(const char *fieldname, const u8 **cursor, size_t *plen)
{
	printf("(msg_name=%s)\n", "tlv4");
	
	printf("cltv_delta=");
	u16 cltv_delta = fromwire_u16(cursor, plen);
	
	printwire_u16(tal_fmt(NULL, "%s.cltv_delta", fieldname), &cltv_delta); 
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}
static void printwire_tlv_test_n1_tlv1(const char *fieldname, const u8 **cursor, size_t *plen)
{
	printf("(msg_name=%s)\n", "tlv1");
	
	printf("amount_msat=");
	u64 amount_msat = fromwire_tu64(cursor, plen);
	
	printwire_u64(tal_fmt(NULL, "%s.amount_msat", fieldname), &amount_msat); 
	if (!*cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 
}

static const struct tlv_print_record_type print_tlvs_test_n1[] = {
	{ 3, printwire_tlv_test_n1_tlv3 },
	{ 2, printwire_tlv_test_n1_tlv2 },
	{ 254, printwire_tlv_test_n1_tlv4 },
	{ 1, printwire_tlv_test_n1_tlv1 },
};
void printwire_test_msg(const char *fieldname, const u8 *cursor)
{

	size_t plen = tal_count(cursor);
	if (fromwire_u16(&cursor, &plen) != WIRE_TEST_MSG) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("test_arr_u8=");
	printwire_u8_array(tal_fmt(NULL, "%s.test_arr_u8", fieldname), &cursor, &plen, 10);

	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_arr_assignable=");
	printf("[");
	for (size_t i = 0; i < 5; i++) {
		u16 v;
		v = fromwire_u16(&cursor, &plen);
		if (!*cursor) {
			printf("**TRUNCATED**\n");
			return;
		}
		printwire_u16(tal_fmt(NULL, "%s.test_arr_assignable", fieldname), &v);
	}
	printf("]");

	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u16 len_var_u8 = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_var_len_u8_arr=");
	printwire_u8_array(tal_fmt(NULL, "%s.test_var_len_u8_arr", fieldname), &cursor, &plen, len_var_u8);

	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u16 len_var_ass = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_var_len_ass_arr=");
	printf("[");
	for (size_t i = 0; i < len_var_ass; i++) {
		u32 v;
		v = fromwire_u32(&cursor, &plen);
		if (!*cursor) {
			printf("**TRUNCATED**\n");
			return;
		}
		printwire_u32(tal_fmt(NULL, "%s.test_var_len_ass_arr", fieldname), &v);
	}
	printf("]");

	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_struct_arr=");
	printf("[");
	for (size_t i = 0; i < 10; i++) {
		printf("{\n");
		printwire_test_short_id(tal_fmt(NULL, "%s.test_struct_arr", fieldname), &cursor, &plen);
		printf("}\n");
	}
	printf("]");

	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u16 len_test_struct_varlen = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_struct_varlen=");
	printf("[");
	for (size_t i = 0; i < len_test_struct_varlen; i++) {
		printf("{\n");
		printwire_test_short_id(tal_fmt(NULL, "%s.test_struct_varlen", fieldname), &cursor, &plen);
		printf("}\n");
	}
	printf("]");

	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	u16 len_varsize_struct = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_varsize_struct_varlen=");
	printf("[");
	for (size_t i = 0; i < len_varsize_struct; i++) {
		printf("{\n");
		printwire_test_features(tal_fmt(NULL, "%s.test_varsize_struct_varlen", fieldname), &cursor, &plen);
		printf("}\n");
	}
	printf("]");

	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_assignable=");
	u16 test_assignable = fromwire_u16(&cursor, &plen);
	
	printwire_u16(tal_fmt(NULL, "%s.test_assignable", fieldname), &test_assignable); 
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_enum=");
	enum test_enum test_enum = fromwire_test_enum(&cursor, &plen);
	
	printwire_test_enum(tal_fmt(NULL, "%s.test_enum", fieldname), &test_enum); 
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_struct=");
	printf("{\n");
	printwire_test_short_id(tal_fmt(NULL, "%s.test_struct", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_varsize_struct=");
	printf("{\n");
	printwire_test_features(tal_fmt(NULL, "%s.test_varsize_struct", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_optional_assignable=");
	u32 test_optional_assignable = fromwire_u32(&cursor, &plen);
	
	printwire_u32(tal_fmt(NULL, "%s.test_optional_assignable", fieldname), &test_optional_assignable); 
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 	printf("test_optional_struct=");
	printf("{\n");
	printwire_test_short_id(tal_fmt(NULL, "%s.test_optional_struct", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_optional_varsize_struct=");
	printf("{\n");
	printwire_test_features(tal_fmt(NULL, "%s.test_optional_varsize_struct", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_sbt_struct_nested=");
	printf("{\n");
	printwire_subtype_nested(tal_fmt(NULL, "%s.test_sbt_struct_nested", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_sbt_varsize_struct=");
	printf("{\n");
	printwire_subtype_varsize_struct(tal_fmt(NULL, "%s.test_sbt_varsize_struct", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_sbt_varsize_var_assign=");
	printf("{\n");
	printwire_subtype_var_assign(tal_fmt(NULL, "%s.test_sbt_varsize_var_assign", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_sbt_var_len=");
	printf("{\n");
	printwire_subtype_var_len(tal_fmt(NULL, "%s.test_sbt_var_len", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_sbt_varlen_varsize=");
	printf("{\n");
	printwire_subtype_varlen_varsize(tal_fmt(NULL, "%s.test_sbt_varlen_varsize", fieldname), &cursor, &plen);
	printf("}\n");
	printf("test_sbt_arrays=");
	printf("{\n");
	printwire_subtype_arrays(tal_fmt(NULL, "%s.test_sbt_arrays", fieldname), &cursor, &plen);
	printf("}\n");
	if (plen <= 0)
		return;
	printf("(option_short_id):");
	printf("extension_1=");
	printf("{\n");
	printwire_test_features(tal_fmt(NULL, "%s.extension_1", fieldname), &cursor, &plen);
	printf("}\n");
	if (plen <= 0)
		return;
	printf("(option_one,option_two):");
	printf("extension_2=");
	printf("{\n");
	printwire_test_short_id(tal_fmt(NULL, "%s.extension_2", fieldname), &cursor, &plen);
	printf("}\n");


	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}
void printwire_test_tlv1(const char *fieldname, const u8 *cursor)
{

	size_t plen = tal_count(cursor);
	if (fromwire_u16(&cursor, &plen) != WIRE_TEST_TLV1) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("test_struct=");
	printf("{\n");
	printwire_test_short_id(tal_fmt(NULL, "%s.test_struct", fieldname), &cursor, &plen);
	printf("}\n");
	printf("tlv=");
	printwire_tlvs(tal_fmt(NULL, "%s.tlv", fieldname), &cursor, &plen, print_tlvs_test_n1, ARRAY_SIZE(print_tlvs_test_n1));


	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}
void printwire_test_ifdef(const char *fieldname, const u8 *cursor)
{

	size_t plen = tal_count(cursor);
	if (fromwire_u16(&cursor, &plen) != WIRE_TEST_IFDEF) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("is_def=");
	u32 is_def = fromwire_u32(&cursor, &plen);
	
	printwire_u32(tal_fmt(NULL, "%s.is_def", fieldname), &is_def); 
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
 

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}
void printwire_test_tlv2(const char *fieldname, const u8 *cursor)
{

	size_t plen = tal_count(cursor);
	if (fromwire_u16(&cursor, &plen) != WIRE_TEST_TLV2) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("tlv=");
	printwire_tlvs(tal_fmt(NULL, "%s.tlv", fieldname), &cursor, &plen, print_tlvs_test_n2, ARRAY_SIZE(print_tlvs_test_n2));


	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}
void printwire_test_tlv3(const char *fieldname, const u8 *cursor)
{

	size_t plen = tal_count(cursor);
	if (fromwire_u16(&cursor, &plen) != WIRE_TEST_TLV3) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("tlv=");
	printwire_tlvs(tal_fmt(NULL, "%s.tlv", fieldname), &cursor, &plen, print_tlvs_test_n3, ARRAY_SIZE(print_tlvs_test_n3));


	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printtest_type_tlv_message(const char *tlv_name, const u8 *msg) {
	size_t plen;
	plen = tal_count(msg);
	if (strcmp(tlv_name, "test_n2") == 0) {
		printwire_tlvs(tlv_name, &msg, &plen, print_tlvs_test_n2, ARRAY_SIZE(print_tlvs_test_n2));
	}
	plen = tal_count(msg);
	if (strcmp(tlv_name, "test_n3") == 0) {
		printwire_tlvs(tlv_name, &msg, &plen, print_tlvs_test_n3, ARRAY_SIZE(print_tlvs_test_n3));
	}
	plen = tal_count(msg);
	if (strcmp(tlv_name, "test_n1") == 0) {
		printwire_tlvs(tlv_name, &msg, &plen, print_tlvs_test_n1, ARRAY_SIZE(print_tlvs_test_n1));
	}
}

