struct {
	enum output_type v;
	const char *name;
} enum_output_type_names[] = {
	{ FUNDING_OUTPUT, "FUNDING_OUTPUT" },
	{ OUTPUT_TO_US, "OUTPUT_TO_US" },
	{ DELAYED_OUTPUT_TO_THEM, "DELAYED_OUTPUT_TO_THEM" },
	{ DELAYED_OUTPUT_TO_US, "DELAYED_OUTPUT_TO_US" },
	{ OUTPUT_TO_THEM, "OUTPUT_TO_THEM" },
	{ THEIR_HTLC, "THEIR_HTLC" },
	{ OUR_HTLC, "OUR_HTLC" },
	{ ELEMENTS_FEE, "ELEMENTS_FEE" },
	{ 0, NULL } };
struct {
	enum tx_type v;
	const char *name;
} enum_tx_type_names[] = {
	{ FUNDING_TRANSACTION, "FUNDING_TRANSACTION" },
	{ MUTUAL_CLOSE, "MUTUAL_CLOSE" },
	{ THEIR_UNILATERAL, "THEIR_UNILATERAL" },
	{ UNKNOWN_UNILATERAL, "UNKNOWN_UNILATERAL" },
	{ OUR_UNILATERAL, "OUR_UNILATERAL" },
	{ THEIR_REVOKED_UNILATERAL, "THEIR_REVOKED_UNILATERAL" },
	{ THEIR_HTLC_TIMEOUT_TO_THEM, "THEIR_HTLC_TIMEOUT_TO_THEM" },
	{ THEIR_HTLC_FULFILL_TO_US, "THEIR_HTLC_FULFILL_TO_US" },
	{ OUR_HTLC_TIMEOUT_TO_US, "OUR_HTLC_TIMEOUT_TO_US" },
	{ OUR_HTLC_FULFILL_TO_THEM, "OUR_HTLC_FULFILL_TO_THEM" },
	{ OUR_HTLC_TIMEOUT_TX, "OUR_HTLC_TIMEOUT_TX" },
	{ OUR_HTLC_SUCCESS_TX, "OUR_HTLC_SUCCESS_TX" },
	{ OUR_DELAYED_RETURN_TO_WALLET, "OUR_DELAYED_RETURN_TO_WALLET" },
	{ OUR_PENALTY_TX, "OUR_PENALTY_TX" },
	{ IGNORING_TINY_PAYMENT, "IGNORING_TINY_PAYMENT" },
	{ SELF, "SELF" },
	{ UNKNOWN_TXTYPE, "UNKNOWN_TXTYPE" },
	{ 0, NULL } };
