/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */
/* Original template can be found at tools/gen/header_template */

#ifndef LIGHTNING_CLOSINGD_GEN_CLOSING_WIRE_H
#define LIGHTNING_CLOSINGD_GEN_CLOSING_WIRE_H
#include <ccan/tal/tal.h>
#include <wire/tlvstream.h>
#include <wire/wire.h>
#include <common/cryptomsg.h>
#include <common/htlc_wire.h>
#include <common/per_peer_state.h>

enum closing_wire_type {
        /*  Begin!  (passes peer fd */
        WIRE_CLOSING_INIT = 2001,
        /*  We received an offer */
        WIRE_CLOSING_RECEIVED_SIGNATURE = 2002,
        WIRE_CLOSING_RECEIVED_SIGNATURE_REPLY = 2102,
        /*  Negotiations complete */
        WIRE_CLOSING_COMPLETE = 2004,
};

const char *closing_wire_type_name(int e);


/* WIRE: CLOSING_INIT */
/*  Begin!  (passes peer fd */
u8 *towire_closing_init(const tal_t *ctx, const struct chainparams *chainparams, const struct per_peer_state *pps, const struct bitcoin_txid *funding_txid, u16 funding_txout, struct amount_sat funding_satoshi, const struct pubkey *local_fundingkey, const struct pubkey *remote_fundingkey, enum side funder, struct amount_sat local_sat, struct amount_sat remote_sat, struct amount_sat our_dust_limit, struct amount_sat min_fee_satoshi, struct amount_sat fee_limit_satoshi, struct amount_sat initial_fee_satoshi, const u8 *local_scriptpubkey, const u8 *remote_scriptpubkey, bool reconnected, u64 next_index_local, u64 next_index_remote, u64 revocations_received, const u8 *channel_reestablish, const struct secret *last_remote_secret, bool dev_fast_gossip);
bool fromwire_closing_init(const tal_t *ctx, const void *p, const struct chainparams **chainparams, struct per_peer_state **pps, struct bitcoin_txid *funding_txid, u16 *funding_txout, struct amount_sat *funding_satoshi, struct pubkey *local_fundingkey, struct pubkey *remote_fundingkey, enum side *funder, struct amount_sat *local_sat, struct amount_sat *remote_sat, struct amount_sat *our_dust_limit, struct amount_sat *min_fee_satoshi, struct amount_sat *fee_limit_satoshi, struct amount_sat *initial_fee_satoshi, u8 **local_scriptpubkey, u8 **remote_scriptpubkey, bool *reconnected, u64 *next_index_local, u64 *next_index_remote, u64 *revocations_received, u8 **channel_reestablish, struct secret *last_remote_secret, bool *dev_fast_gossip);

/* WIRE: CLOSING_RECEIVED_SIGNATURE */
/*  We received an offer */
u8 *towire_closing_received_signature(const tal_t *ctx, const struct bitcoin_signature *signature, const struct bitcoin_tx *tx);
bool fromwire_closing_received_signature(const tal_t *ctx, const void *p, struct bitcoin_signature *signature, struct bitcoin_tx **tx);

/* WIRE: CLOSING_RECEIVED_SIGNATURE_REPLY */
u8 *towire_closing_received_signature_reply(const tal_t *ctx, const struct bitcoin_txid *closing_txid);
bool fromwire_closing_received_signature_reply(const void *p, struct bitcoin_txid *closing_txid);

/* WIRE: CLOSING_COMPLETE */
/*  Negotiations complete */
u8 *towire_closing_complete(const tal_t *ctx);
bool fromwire_closing_complete(const void *p);


#endif /* LIGHTNING_CLOSINGD_GEN_CLOSING_WIRE_H */

