struct {
	enum channel_state v;
	const char *name;
} enum_channel_state_names[] = {
	{ CHANNELD_AWAITING_LOCKIN, "CHANNELD_AWAITING_LOCKIN" },
	{ CHANNELD_NORMAL, "CHANNELD_NORMAL" },
	{ CHANNELD_SHUTTING_DOWN, "CHANNELD_SHUTTING_DOWN" },
	{ CLOSINGD_SIGEXCHANGE, "CLOSINGD_SIGEXCHANGE" },
	{ CLOSINGD_COMPLETE, "CLOSINGD_COMPLETE" },
	{ AWAITING_UNILATERAL, "AWAITING_UNILATERAL" },
	{ FUNDING_SPEND_SEEN, "FUNDING_SPEND_SEEN" },
	{ ONCHAIN, "ONCHAIN" },
	{ CLOSED, "CLOSED" },
	{ 0, NULL } };
