struct {
	enum htlc_state v;
	const char *name;
} enum_htlc_state_names[] = {
	{ SENT_ADD_HTLC, "SENT_ADD_HTLC" },
	{ SENT_ADD_COMMIT, "SENT_ADD_COMMIT" },
	{ RCVD_ADD_REVOCATION, "RCVD_ADD_REVOCATION" },
	{ RCVD_ADD_ACK_COMMIT, "RCVD_ADD_ACK_COMMIT" },
	{ SENT_ADD_ACK_REVOCATION, "SENT_ADD_ACK_REVOCATION" },
	{ RCVD_REMOVE_HTLC, "RCVD_REMOVE_HTLC" },
	{ RCVD_REMOVE_COMMIT, "RCVD_REMOVE_COMMIT" },
	{ SENT_REMOVE_REVOCATION, "SENT_REMOVE_REVOCATION" },
	{ SENT_REMOVE_ACK_COMMIT, "SENT_REMOVE_ACK_COMMIT" },
	{ RCVD_REMOVE_ACK_REVOCATION, "RCVD_REMOVE_ACK_REVOCATION" },
	{ RCVD_ADD_HTLC, "RCVD_ADD_HTLC" },
	{ RCVD_ADD_COMMIT, "RCVD_ADD_COMMIT" },
	{ SENT_ADD_REVOCATION, "SENT_ADD_REVOCATION" },
	{ SENT_ADD_ACK_COMMIT, "SENT_ADD_ACK_COMMIT" },
	{ RCVD_ADD_ACK_REVOCATION, "RCVD_ADD_ACK_REVOCATION" },
	{ SENT_REMOVE_HTLC, "SENT_REMOVE_HTLC" },
	{ SENT_REMOVE_COMMIT, "SENT_REMOVE_COMMIT" },
	{ RCVD_REMOVE_REVOCATION, "RCVD_REMOVE_REVOCATION" },
	{ RCVD_REMOVE_ACK_COMMIT, "RCVD_REMOVE_ACK_COMMIT" },
	{ SENT_REMOVE_ACK_REVOCATION, "SENT_REMOVE_ACK_REVOCATION" },
	{ HTLC_STATE_INVALID, "HTLC_STATE_INVALID" },
	{ 0, NULL } };
