/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */
/* Original template can be found at tools/gen/header_template */

#ifndef LIGHTNING_GOSSIPD_GEN_GOSSIP_STORE_H
#define LIGHTNING_GOSSIPD_GEN_GOSSIP_STORE_H
#include <ccan/tal/tal.h>
#include <wire/tlvstream.h>
#include <wire/wire.h>

enum gossip_store_type {
        WIRE_GOSSIP_STORE_PRIVATE_UPDATE = 4102,
        /*  This always follows the channel_announce. */
        WIRE_GOSSIP_STORE_CHANNEL_AMOUNT = 4101,
};

const char *gossip_store_type_name(int e);


/* WIRE: GOSSIP_STORE_PRIVATE_UPDATE */
u8 *towire_gossip_store_private_update(const tal_t *ctx, const u8 *update);
bool fromwire_gossip_store_private_update(const tal_t *ctx, const void *p, u8 **update);

/* WIRE: GOSSIP_STORE_CHANNEL_AMOUNT */
/*  This always follows the channel_announce. */
u8 *towire_gossip_store_channel_amount(const tal_t *ctx, struct amount_sat satoshis);
bool fromwire_gossip_store_channel_amount(const void *p, struct amount_sat *satoshis);


#endif /* LIGHTNING_GOSSIPD_GEN_GOSSIP_STORE_H */

